version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - starter
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8008:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - starter
networks:
  starter:
    driver: bridge
